apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: sg
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: helloworld@naver.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kimseonguk-com-tls
  namespace: sg
spec: 
  secretName: kimseonguk-com-tls
  duration: 2160h #90일
  renewBefore: 360h #15일전에 갱신
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: server.kimseonguk197.shop
  dnsNames:
  - server.kimseonguk197.shop

  